# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QSizePolicy,
    QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(800, 600)
        self.temp_powertrain_ant = QLabel(Widget)
        self.temp_powertrain_ant.setObjectName(u"temp_powertrain_ant")
        self.temp_powertrain_ant.setGeometry(QRect(580, 510, 181, 71))
        font = QFont()
        font.setPointSize(40)
        self.temp_powertrain_ant.setFont(font)
        self.temp_powertrain_ant.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(Widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(340, 330, 111, 41))
        font1 = QFont()
        font1.setPointSize(20)
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.tens_lowV = QLabel(Widget)
        self.tens_lowV.setObjectName(u"tens_lowV")
        self.tens_lowV.setGeometry(QRect(580, 50, 161, 51))
        font2 = QFont()
        font2.setPointSize(30)
        self.tens_lowV.setFont(font2)
        self.tens_lowV.setAlignment(Qt.AlignCenter)
        self.tens_max_cella = QLabel(Widget)
        self.tens_max_cella.setObjectName(u"tens_max_cella")
        self.tens_max_cella.setGeometry(QRect(550, 180, 211, 71))
        self.tens_max_cella.setFont(font)
        self.tens_max_cella.setAlignment(Qt.AlignCenter)
        self.temp_powertrain_post = QLabel(Widget)
        self.temp_powertrain_post.setObjectName(u"temp_powertrain_post")
        self.temp_powertrain_post.setGeometry(QRect(50, 510, 181, 71))
        self.temp_powertrain_post.setFont(font)
        self.temp_powertrain_post.setAlignment(Qt.AlignCenter)
        self.tens_min_cella = QLabel(Widget)
        self.tens_min_cella.setObjectName(u"tens_min_cella")
        self.tens_min_cella.setGeometry(QRect(550, 280, 211, 71))
        self.tens_min_cella.setFont(font)
        self.tens_min_cella.setAlignment(Qt.AlignCenter)
        self.temp_batteria = QLabel(Widget)
        self.temp_batteria.setObjectName(u"temp_batteria")
        self.temp_batteria.setGeometry(QRect(310, 520, 181, 61))
        self.temp_batteria.setFont(font)
        self.temp_batteria.setAlignment(Qt.AlignCenter)
        self.velocita = QLabel(Widget)
        self.velocita.setObjectName(u"velocita")
        self.velocita.setGeometry(QRect(280, 220, 231, 111))
        font3 = QFont()
        font3.setPointSize(67)
        font3.setUnderline(False)
        self.velocita.setFont(font3)
        self.velocita.setLayoutDirection(Qt.LeftToRight)
        self.velocita.setAlignment(Qt.AlignCenter)
        self.tempo = QLabel(Widget)
        self.tempo.setObjectName(u"tempo")
        self.tempo.setGeometry(QRect(20, 50, 211, 41))
        self.tempo.setFont(font2)
        self.tempo.setAlignment(Qt.AlignCenter)
        self.perc_batteria = QLabel(Widget)
        self.perc_batteria.setObjectName(u"perc_batteria")
        self.perc_batteria.setGeometry(QRect(20, 190, 241, 101))
        font4 = QFont()
        font4.setPointSize(50)
        self.perc_batteria.setFont(font4)
        self.perc_batteria.setAlignment(Qt.AlignCenter)
        self.temp_max_cella = QLabel(Widget)
        self.temp_max_cella.setObjectName(u"temp_max_cella")
        self.temp_max_cella.setGeometry(QRect(550, 380, 211, 71))
        self.temp_max_cella.setFont(font)
        self.temp_max_cella.setAlignment(Qt.AlignCenter)
        self.tens_media_batteria = QLabel(Widget)
        self.tens_media_batteria.setObjectName(u"tens_media_batteria")
        self.tens_media_batteria.setGeometry(QRect(20, 310, 241, 101))
        self.tens_media_batteria.setFont(font4)
        self.tens_media_batteria.setAlignment(Qt.AlignCenter)
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(52, 170, 181, 31))
        font5 = QFont()
        font5.setPointSize(15)
        self.label.setFont(font5)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 20, 181, 31))
        self.label_2.setFont(font5)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 300, 181, 31))
        self.label_3.setFont(font5)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(570, 160, 181, 31))
        self.label_4.setFont(font5)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(570, 260, 181, 31))
        self.label_5.setFont(font5)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(570, 360, 181, 31))
        self.label_6.setFont(font5)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(310, 200, 181, 31))
        self.label_7.setFont(font5)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(Widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 490, 211, 31))
        self.label_11.setFont(font5)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(Widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(310, 490, 181, 31))
        self.label_13.setFont(font5)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(Widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(560, 490, 211, 31))
        self.label_14.setFont(font5)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(530, 10, 261, 41))
        self.label_8.setFont(font5)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.line = QFrame(Widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-3, 460, 841, 20))
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QFrame.HLine)
        self.line_2 = QFrame(Widget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-50, 110, 861, 20))
        self.line_2.setFrameShadow(QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_3 = QFrame(Widget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(260, 120, 21, 491))
        self.line_3.setFrameShadow(QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_4 = QFrame(Widget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(510, 120, 21, 491))
        self.line_4.setFrameShadow(QFrame.Plain)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QFrame.VLine)

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.temp_powertrain_ant.setText(QCoreApplication.translate("Widget", u"99\u00b0", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"Km/h", None))
        self.tens_lowV.setText(QCoreApplication.translate("Widget", u"99.99v", None))
        self.tens_max_cella.setText(QCoreApplication.translate("Widget", u"99.99v", None))
        self.temp_powertrain_post.setText(QCoreApplication.translate("Widget", u"99\u00b0", None))
        self.tens_min_cella.setText(QCoreApplication.translate("Widget", u"99.99v", None))
        self.temp_batteria.setText(QCoreApplication.translate("Widget", u"99\u00b0", None))
        self.velocita.setText(QCoreApplication.translate("Widget", u"999", None))
        self.tempo.setText(QCoreApplication.translate("Widget", u"99m 99s", None))
        self.perc_batteria.setText(QCoreApplication.translate("Widget", u"999%", None))
        self.temp_max_cella.setText(QCoreApplication.translate("Widget", u"99\u00b0", None))
        self.tens_media_batteria.setText(QCoreApplication.translate("Widget", u"99.99v", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Batteria", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Tempo", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"Tensione", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Tensione Max cella", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Tensione Min cella", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Temp Max cella", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Velocit\u00e0", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Temp Powertrain Post", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Temp Batteria", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Temp Powertrain Ant", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Tensione Low Voltage", None))
    # retranslateUi

